# Generated by Django 4.1.7 on 2023-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("job_company_name", models.CharField(max_length=100)),
                ("logo_url", models.CharField(max_length=100)),
                ("job_description", models.CharField(max_length=20000)),
                ("location", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("salary_range", models.CharField(max_length=100)),
                ("post_time", models.CharField(max_length=100)),
                ("fill_date", models.CharField(default="2023-03-10", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JobTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_tags",
                        to="jobscraper.post",
                    ),
                ),
            ],
        ),
    ]
