# Generated by Django 4.1.7 on 2023-03-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobscraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="application_link",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="fill_date",
            field=models.CharField(default="2023-03-14", max_length=100),
        ),
    ]
