# Generated by Django 4.1.7 on 2023-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobscraper", "0002_post_application_link_alter_post_fill_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="fill_date",
            field=models.CharField(default="2023-05-11", max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="job_description",
            field=models.TextField(),
        ),
    ]
